name: Deploy and Publish Package

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ main ]

env:
  OPENAI__APIKEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI__APIKEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release

  publish:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        source-url: https://nuget.pkg.github.com/taviovieira89/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Create NuGet Package
      run: |
        dotnet pack src/Domain/AIChatAgent.Domain.csproj -c Release -o packages
        dotnet pack src/Infrastructure/AIChatAgent.Infrastructure.csproj -c Release -o packages
        dotnet pack src/Application/AIChatAgent.Application.csproj -c Release -o packages

    - name: Publish NuGet Package
      run: |
        for f in ./packages/*.nupkg
        do
          dotnet nuget push $f --api-key ${{secrets.GITHUB_TOKEN}} --source "https://nuget.pkg.github.com/taviovieira89/index.json" --skip-duplicate
        done