name: Test APIs

on:
  workflow_dispatch:  # Permite execução manual do workflow
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - '.github/workflows/**'

env:
  OPENAI__APIKEY: ${{ secrets.OPENAI_API_KEY }}
  GEMINI__APIKEY: ${{ secrets.GEMINI_API_KEY }}

jobs:
  test-apis:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test OpenAI API
      run: |
        dotnet run --project src/Api/AIChatAgent.csproj -- test-api openai "Hello, how are you?"
      env:
        CHATPROVIDER: "OpenAI"
        
    - name: Test Gemini API
      run: |
        dotnet run --project src/Api/AIChatAgent.csproj -- test-api gemini "Hello, how are you?"
      env:
        CHATPROVIDER: "Gemini"